services:
  mongodb:
    image: mongo:8
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: erp
    ports:
      - "27017:27017"
    volumes:
      - erp-mongodb-data:/data/db

volumes:
  erp-mongodb-data: