import type { RequestHandler } from 'express';
import { ZodError, z } from 'zod';
import { CRMError, completeActivity, createActivity, createLead, createOpportunity, listActivities, listLeads, listOpportunities, updateLead, updateOpportunity } from '../services/crm.service.js';
import { completeCRMActivitySchema, createCRMActivitySchema, createLeadSchema, createOpportunitySchema, listCRMActivitiesSchema, updateLeadSchema, updateOpportunitySchema } from '../validators/crm.validators.js';

function tenant(req: Parameters<RequestHandler>[0], res: Parameters<RequestHandler>[1]) { if (!req.user?.companyId || !req.user.branchId) { res.status(403).json({ success: false, message: 'Usuario sin empresa o sucursal asignada', error: { code: 'TENANT_REQUIRED', details: [] } }); return undefined; } return { companyId: req.user.companyId, branchId: req.user.branchId }; }
function handle(error: unknown, res: Parameters<RequestHandler>[1], next: Parameters<RequestHandler>[2]) {
  if (error instanceof ZodError) { res.status(422).json({ success: false, message: 'Datos invalidos', error: { code: 'VALIDATION_ERROR', details: error.issues } }); return; }
  if (error instanceof CRMError) { const status = ['LEAD_NOT_FOUND', 'OPPORTUNITY_NOT_FOUND', 'ACTIVITY_NOT_FOUND'].includes(error.code) ? 404 : error.code === 'CRM_REFERENCE_INVALID' ? 422 : 409; res.status(status).json({ success: false, message: error.message, error: { code: error.code, details: [] } }); return; }
  next(error);
}
export const listLeadsController: RequestHandler = async (req, res, next) => { try { const t = tenant(req, res); if (!t) return; res.status(200).json({ success: true, message: 'Leads consultados', data: await listLeads(t) }); } catch (e) { next(e); } };
export const createLeadController: RequestHandler = async (req, res, next) => { try { const t = tenant(req, res); if (!t) return; res.status(201).json({ success: true, message: 'Lead creado', data: await createLead(createLeadSchema.parse(req.body), req.user!.sub, t) }); } catch (e) { handle(e, res, next); } };
export const updateLeadController: RequestHandler = async (req, res, next) => { try { const t = tenant(req, res); if (!t) return; const number = z.string().trim().min(1).max(40).parse(req.params.leadNumber); res.status(200).json({ success: true, message: 'Lead actualizado', data: await updateLead(number, updateLeadSchema.parse(req.body), t) }); } catch (e) { handle(e, res, next); } };
export const listOpportunitiesController: RequestHandler = async (req, res, next) => { try { const t = tenant(req, res); if (!t) return; res.status(200).json({ success: true, message: 'Oportunidades consultadas', data: await listOpportunities(t) }); } catch (e) { next(e); } };
export const createOpportunityController: RequestHandler = async (req, res, next) => { try { const t = tenant(req, res); if (!t) return; res.status(201).json({ success: true, message: 'Oportunidad creada', data: await createOpportunity(createOpportunitySchema.parse(req.body), req.user!.sub, t) }); } catch (e) { handle(e, res, next); } };
export const updateOpportunityController: RequestHandler = async (req, res, next) => { try { const t = tenant(req, res); if (!t) return; const number = z.string().trim().min(1).max(40).parse(req.params.opportunityNumber); res.status(200).json({ success: true, message: 'Oportunidad actualizada', data: await updateOpportunity(number, updateOpportunitySchema.parse(req.body), t) }); } catch (e) { handle(e, res, next); } };
export const listActivitiesController: RequestHandler = async (req, res, next) => { try { const t = tenant(req, res); if (!t) return; const filter = listCRMActivitiesSchema.parse(req.query); res.status(200).json({ success: true, message: 'Actividades consultadas', data: await listActivities(filter.entityType, filter.entityNumber, t) }); } catch (e) { handle(e, res, next); } };
export const createActivityController: RequestHandler = async (req, res, next) => { try { const t = tenant(req, res); if (!t) return; res.status(201).json({ success: true, message: 'Actividad creada', data: await createActivity(createCRMActivitySchema.parse(req.body), req.user!.sub, t) }); } catch (e) { handle(e, res, next); } };
export const completeActivityController: RequestHandler = async (req, res, next) => { try { const t = tenant(req, res); if (!t) return; const number = z.string().trim().min(1).max(40).parse(req.params.activityNumber); res.status(200).json({ success: true, message: 'Actividad completada', data: await completeActivity(number, completeCRMActivitySchema.parse(req.body), t) }); } catch (e) { handle(e, res, next); } };
